package com.arnyminerz.escalaralcoiaicomtat.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF506601)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd2ee81)
val md_theme_light_onPrimaryContainer = Color(0xFF151f00)
val md_theme_light_secondary = Color(0xFF5b6147)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdfe6c4)
val md_theme_light_onSecondaryContainer = Color(0xFF181e09)
val md_theme_light_tertiary = Color(0xFF39665e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbdece2)
val md_theme_light_onTertiaryContainer = Color(0xFF00201b)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefcf4)
val md_theme_light_onBackground = Color(0xFF1b1c17)
val md_theme_light_surface = Color(0xFFfefcf4)
val md_theme_light_onSurface = Color(0xFF1b1c17)
val md_theme_light_surfaceVariant = Color(0xFFe3e4d4)
val md_theme_light_onSurfaceVariant = Color(0xFF46483c)
val md_theme_light_outline = Color(0xFF76786a)
val md_theme_light_inverseOnSurface = Color(0xFFf3f1e9)
val md_theme_light_inverseSurface = Color(0xFF30312b)

val md_theme_dark_primary = Color(0xFFb6d168)
val md_theme_dark_onPrimary = Color(0xFF273500)
val md_theme_dark_primaryContainer = Color(0xFF3a4d00)
val md_theme_dark_onPrimaryContainer = Color(0xFFd2ee81)
val md_theme_dark_secondary = Color(0xFFc3caa9)
val md_theme_dark_onSecondary = Color(0xFF2d331c)
val md_theme_dark_secondaryContainer = Color(0xFF434931)
val md_theme_dark_onSecondaryContainer = Color(0xFFdfe6c4)
val md_theme_dark_tertiary = Color(0xFFa0d0c6)
val md_theme_dark_onTertiary = Color(0xFF023730)
val md_theme_dark_tertiaryContainer = Color(0xFF214e47)
val md_theme_dark_onTertiaryContainer = Color(0xFFbdece2)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1c17)
val md_theme_dark_onBackground = Color(0xFFe4e2db)
val md_theme_dark_surface = Color(0xFF1b1c17)
val md_theme_dark_onSurface = Color(0xFFe4e2db)
val md_theme_dark_surfaceVariant = Color(0xFF46483c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c8b8)
val md_theme_dark_outline = Color(0xFF909283)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1c17)
val md_theme_dark_inverseSurface = Color(0xFFe4e2db)

val seed = Color(0xFF506602)
val error = Color(0xFFba1b1b)